// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy, useSnapshot, snapshot, subscribe,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
} from '/Users/yxs/simple-monorepo-with-umi/node_modules/.pnpm/@umijs+valtio@1.0.0_react@18.0.0/node_modules/@umijs/valtio';
